app-service-auth:
  id: application.service.app-service-auth
  name: Authentication Service
  type: service
  documentation: Manages user authentication
app-service-1:
  id: application.service.app-service-1
  name: Service 1
  type: service
  documentation: Service number 1
app-service-2:
  id: application.service.app-service-2
  name: Service 2
  type: service
  documentation: Service number 2
app-service-3:
  id: application.service.app-service-3
  name: Service 3
  type: service
  documentation: Service number 3
app-service-4:
  id: application.service.app-service-4
  name: Service 4
  type: service
  documentation: Service number 4
app-service-5:
  id: application.service.app-service-5
  name: Service 5
  type: service
  documentation: Service number 5
app-service-cs1-2:
  id: application.service.app-service-cs1-2
  name: CS1 Service 2
  type: service
app-service-new-2:
  id: application.service.app-service-new-2
  name: New Service 2
  type: service
